### ISSUE TITLE
prettify landing page

### ISSUE THREAD

**Issue by edublancas** [ploomber/notebooks-academy#2]
This site is deployed [here](https://notebooks.academy/en/latest/intro.html).

The landing page needs some work.

- [ ] add some CSS, so the div for subscribing to the newsletter looks good
- [ ] Change the links to Twitter and LinkedIn for the actual logos and center them

We're using [jupyter-book](https://github.com/executablebooks/jupyter-book) so check out their docs to see how to do this.

**Comment by e1ha** [comment]
For the first task, what CSS should I be adding for the div to subscribing to the newsletter? For the second task, I don't see any Twitter and Linkedin logos on the landing page.

**Comment by edublancas** [comment]
> what CSS should I be adding for the div to subscribing to the newsletter?

It's open; feel free to suggest something. it should be centered and follow the style of the rest of the theme

> For the second task, I don't see any Twitter and Linkedin logos on the landing page.

Please download them and put them under `website/static`

**Comment by e1ha** [comment]
For the css how about putting some space between "Email address" text and the text box where you enter the email address? Also, align the subscribe button with the Email address text and the text box instead of putting it under. Maybe we can even get rid of the "Email address" text since it seems redundant. 

For the second task, when you say download them, do you mean to insert Twitter and Linkedin logos onto the landing page and then replace the bulleted links we currently have right now with the logos instead?

**Comment by edublancas** [comment]
> For the css how about putting some space between "Email address" text and the text box where you enter the email address? Also, align the subscribe button with the Email address text and the text box instead of putting it under. Maybe we can even get rid of the "Email address" text since it seems redundant.

sounds good

> For the second task, when you say download them, do you mean to insert Twitter and Linkedin logos onto the landing page and then replace the bulleted links we currently have right now with the logos instead?

yep
